### ISSUE TITLE
Add ability to import TypeScript translation file

### ISSUE THREAD

**Issue by Alex-D** [intlify/vite-plugin-vue-i18n#35]
For convenience, I want to put my translations in TypeScript files.

This allow me to:

- get autocomplete and typecheck (I've decorated the `t` function on my side)
- use one language as a base (English for example) to know which keys are valid or not and improve maintainability of other localisations
- add comments (OK, JSON5 and YAML allow that too)
- good/simple IDE integration

So, can I just use TypeScript files and get them eat by the vite plugin? Or should I migrate to JSON5 or something, and create a type for my translation keys?

Thank you :)

**Comment by kazupon** [comment]
Thank you for your feedback! 

In vite-plugin-vue-i18n, It's possible technically to support typescript as an i18n resource in vite.
However, I fear that supporting typescript will complicate the integration of the resource with the localization service.

Software globalization involves not only us, the developers, but also the translators. Translators generally do not touch the source code directly, but use tools that support editing of localization services and i18n resources.
Given that ecosystem, I'm not keen on supporting `.ts` in the i18n resource format either.

If you are using typescript, you are probably using VS code. [i18n ally](https://github.com/antfu/i18n-ally) is the best VS code extension for editing i18n resources like json, yaml, etc. This is very useful for completing the key of i18n resources. I recommend you to use this extension. :)
