### ISSUE TITLE
Regression: build error since beta.13

### ISSUE THREAD

**Issue by antfu** [intlify/vite-plugin-vue-i18n#52]
Was working fine in beta.12

```
[vite]: Rollup failed to resolve import "@intlify/shared" from "node_modules/vue-i18n/dist/vue-i18n.runtime.esm-bundler.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
```

Repro: https://github.com/antfu/repro-vite-plugin-vue-i18n-1

**Comment by kazupon** [comment]
Thanks! 😆 
I'll try to check your reproduction repo, and fix it!

**Comment by kazupon** [comment]
@antfu 
It seems to happen in the pnpm environment.
This is strange. 🤔 

I was able to build successfully with npm and yarn.
It seems that vite can't resolve `@intlify/shared` from `node_modules` in pnpm environment.

I'll try to check the docs again.
https://vitejs.dev/guide/dep-pre-bundling.html#automatic-dependency-discovery

**Comment by antfu** [comment]
Oh, with `shamefully-hoist=true` the problem gets resolved... If that couldn't be an easy fix I think I am ok with the workaround 😅

**Comment by kazupon** [comment]
>Default: false
> Type: Boolean

https://pnpm.js.org/en/npmrc#shamefully-hoist

I see, As for hoist's behavior, by default, it's the same as npm and yarn!
Thank you for your feedback!

close
