### ISSUE TITLE
Can support language files of ts｜js files？

### ISSUE THREAD

**Issue by anncwb** [intlify/vite-plugin-vue-i18n#67]
Can support language files of `.ts`｜`js` files?

Currently, only three formats of yaml json json5 are supported. Can provide other extensions or expose interfaces for users to implement by themselves

**Comment by anncwb** [comment]
https://github.com/intlify/vite-plugin-vue-i18n/blob/a914e2a7e955a96bca2930547921a3f1cd1526aa/src/index.ts#L272

Or provide custom parameters for users to customize the compiler

**Comment by kazupon** [comment]
Thank you for your feedback!

Unfortunately, we don't support `js` and `ts` files.

For applications that support i18n in general, you can use locale messages such as vue-i18n to separate messages by locale as i18n resources. It will then work with the localization service to upload and localize the resource.

By using `ts` files  and `js` files for i18n rsources, and with help from vscode, programmers can get better DX.
However, those forms of i18n resources are incompatible with the localization service.
In general, such services do not expect executable formats such as ts and js to be used as i18n resources.

For this reason, vue-i18n (intlify) does not support `ts` and `js` files.

**Comment by anncwb** [comment]
I feel that most people still need to use ts|js, with this restriction we can only give up using this plugin to write plugins by ourselves
