### ISSUE TITLE
esm-bundler build warning with vite 2

### ISSUE THREAD

**Issue by AhsanAbrar** [intlify/vite-plugin-vue-i18n#73]
- `vue-i18n`:  ^9.0.0
- `@intlify/vite-plugin-vue-i18n`: 2.x
 - `vite`: 2.x

**Screenshots**
![Warning!](https://share.codedott.com/img/vite-vue-i18n-warning.png)

why we are seeing this warning with vite 2.x?

```bash
You are running the esm-bundler build of vue-i18n. It is recommended to configure your bundler to explicitly replace feature flag globals with boolean literals to get proper tree-shaking in the final bundle.
```

it should be solved.

**Comment by kazupon** [comment]
same #74

**Comment by kazupon** [comment]
I've just fixed it!
please check lastest version!
https://github.com/intlify/vite-plugin-vue-i18n/releases/tag/v2.0.2
