### ISSUE TITLE
How to use with <script setup>?

### ISSUE THREAD

**Issue by cliqer** [intlify/vite-plugin-vue-i18n#82]
![image](https://user-images.githubusercontent.com/3495993/112221052-e1cabd80-8c1e-11eb-93c4-718366d3f2c7.png)

**Comment by kazupon** [comment]
Thank you for your reporting!

This error has occurred when you don't use `useI18n` at top of `setup` function.

Yes. `vite-plugin-vue-i18n` is setup for Composition API as default.
https://github.com/intlify/vite-plugin-vue-i18n#warning-notice

if you don’t use Composition API yet, I recommend that you read the docs.
https://v3.vuejs.org/guide/composition-api-introduction.html

**Comment by cliqer** [comment]
Thank you @kazupon.

I do use composition api.

I am referring to [<script setup> RFC](https://github.com/vuejs/rfcs/blob/script-setup-2/active-rfcs/0000-script-setup.md) and just trying to figure out the internals of how to make i18n work with it.

I believe it is still a Composition API refactoring but not sure.

Many thanks in advance

**Comment by kazupon** [comment]
I hope you will be able to create nice applications with Vue + vue-i18n. :)
Thanks!

**Comment by cliqer** [comment]
Sorry @kazupon maybe I wasn't clear enough.

How can I use `vite-plugin-vue-i18n` with `<script setup> RFC` composition API?
It keeps throwing error:
```js
Uncaught SyntaxError: Must be called at the top of a `setup` function
```
Is it already possible?
- If so, how?
- If not, will you support it?

**Comment by kazupon** [comment]
Hmm, I seem you are writing correctly codes.
Could you give me minimal reproduction repo, please?

**Comment by cliqer** [comment]
Ah, found it!
While creating a repro figured out my problem:
```ts
// vite.config.ts

import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import vueI18n from '@intlify/vite-plugin-vue-i18n'

export default defineConfig({
  plugins: [
    vue(),
    vueI18n({
      // compositionOnly: true
    })
  ]
})
```

```ts
// main.ts <- Used your "Global" example and it worked

import { createApp } from 'vue'
import { createI18n } from 'vue-i18n'
import App from './App.vue'

const i18n = createI18n({
  locale: 'en'
})

createApp(App).use(i18n).mount('#app')
```

```vue
// App.vue

<template lang="pug">
div
  select(v-model='locale')
    option(value='en') en
    option(value='fr') fr
  div {{ t('waiting_for_connection') }}
</template>

<script setup> // <- RFC implementation (https://github.com/vuejs/rfcs/pull/227)
import { useI18n } from 'vue-i18n'
let { locale, t } = useI18n({
  inheritLocale: true
})
</script>

<i18n lang="yaml">
en:
  waiting_for_connection: "Waiting for connection"
fr:
  waiting_for_connection: "En attente de connexion"
</i18n>
```

Many thanks for your time and great work 👍 
Feel free to include this as an RFC example ;)
