### ISSUE TITLE
Build production issue

### ISSUE THREAD

**Issue by hanhdt** [intlify/vite-plugin-vue-i18n#83]
**Reporting a bug?**
- It's running fine on Dev mode but I got issue when I was tried to build production. Please look at the attachment below.
![Screenshot from 2021-03-24 10-13-54](https://user-images.githubusercontent.com/3414312/112240178-31df6980-8c8b-11eb-98c4-39adee52aeb9.png)

**Module versions (please complete the following information):**
 - `@intlify/vite-plugin-vue-i18n`: 2.0.4
 - `vite`: 2.1.2

Anyone can have ideas about this issue?

Thank you.

**Comment by kazupon** [comment]
Thank you for your reporting!

This issue is vue-i18n-next.
related issue is here
https://github.com/intlify/vue-i18n-next/issues/390

As a workaround, you can fix it to TS 4.1.

**Comment by hanhdt** [comment]
Thanks for quick response.
I will wait for vue-i18n v9.1 release.

**Comment by kazupon** [comment]
I released vue-i18n v9.1 !
latest version is v9.1.1

You can try it! :)
https://github.com/intlify/vue-i18n-next/releases

**Comment by hanhdt** [comment]
I upgraded vue-i18n version and I got these alerts.

**Comment by kazupon** [comment]
I've fixed at vue-i18n v9.1.2 !
Please check it!

BTW, you can avoid type errors of library with using 'skipLibCheck' 😉 
https://www.typescriptlang.org/tsconfig#skipLibCheck

**Comment by hanhdt** [comment]
Yea, I verified it.
Thanks for your advise and fixing quickly.
ありがとうございます。:)
