### ISSUE TITLE
Uncaught ReferenceError: __INTLIFY_PROD_DEVTOOLS__ is not defined

### ISSUE THREAD

**Issue by JereMiO** [intlify/vite-plugin-vue-i18n#86]
Module versions :
 - `@intlify/vite-plugin-vue-i18n`: 2.1.0
 - `vite`: ~2.0.5
 - `vue`: "^3.0.5"
 - `vue-i18n`: "^9.1.0"

Hello,
I have problem when i upload my website.
https://compassionate-euclid-d98a00.netlify.app/

I am encountering a trouble : Uncaught ReferenceError: __INTLIFY_PROD_DEVTOOLS__ is not defined

Is there a problem in my configuration ?

**Comment by kazupon** [comment]
I've released vue-i18n v9.1.1 
https://github.com/intlify/vue-i18n-next/releases/tag/v9.1.1

Please check it!

**Comment by JereMiO** [comment]
It works! Thanks
