### ISSUE TITLE
"messageCompiler is not a function" after building files.

### ISSUE THREAD

**Issue by shufangyi** [intlify/vite-plugin-vue-i18n#91]
**Reporting a bug?**

i want to use `$t` in template section and lifecycle hook functions.
so in vite.config.js

```
vueI18n({
  include: path.resolve(__dirname, ".src/locales/**"),
  compositionOnly: false,
}),
```

it works well in development mode.

but
```
yarn build
yarn serve
```
will report an error!
```
TypeError: messageCompiler is not a function
    at compileMessageFormat (vendor.5894b8cb.js:4759)
    at translate (vendor.5894b8cb.js:4697)
    at vendor.5894b8cb.js:5182
    at wrapWithDeps (vendor.5894b8cb.js:5170)
    at Object.t (vendor.5894b8cb.js:5182)
    at Object.t (vendor.5894b8cb.js:5571)
    at Proxy.$t (vendor.5894b8cb.js:5911)
    at Proxy._sfc_render (index.21a6f879.js:54)
    at renderComponentRoot (vendor.5894b8cb.js:1223)
    at componentEffect (vendor.5894b8cb.js:2437)
logError @ vendor.5894b8cb.js:969
```
 
**Module versions (please complete the following information):**
 - `vue-i18n`: "^9.1.6"
 - `@intlify/vite-plugin-vue-i18n`: 2.1.2
 - `vite`: 2.1.5

**Reproduction Link**

example link 👉 [link](https://github.com/shufangyi/vite-vue/tree/show-vueI18n-vite-build-error) 

**To Reproduce**
1. yarn build
2. yarn serve
3. just open the devtool
 

**Expected behavior**

**Screenshots**
[image](https://drive.google.com/file/d/18bU6OyJhfvMPH6yjXqeO99dOrLc8Szw5/view?usp=sharing)

**Additional context**

**Comment by kazupon** [comment]
@shufangyi 
Could you resolve this issue?

**Comment by shufangyi** [comment]
yeap！
My mis！ I just read the readme again. 

By setting `runtimeOnly: false`, this issue is redolved!

**Comment by kazupon** [comment]
I'm relieved to hear that. :)
enjoy coding!

**Comment by shufangyi** [comment]
thx

**Comment by zhuanghongbin** [comment]
i set

> yeap！
> My mis！ I just read the readme again.
> 
> By setting `runtimeOnly: false`, this issue is resolved!

nice
