### ISSUE TITLE
i have to restart vite server

### ISSUE THREAD

**Issue by mdbetancourt** [intlify/vite-plugin-vue-i18n#93]
Every time i add a new translation i have to reload the vite server to get it

**Module versions (please complete the following information):**
 - `@intlify/vite-plugin-vue-i18n`: 2.1.2
 - `vite`: 2.2.3

You can use reproduction CodeSandbox template: https://codesandbox.io/s/vue-i18n-9-template-h28c0

**To Reproduce**
ex:
1. Start vite server
2. Add a new translation to files

**Expected behavior**
Take the new translation string

**Comment by mseele** [comment]
Same for me. I use the [Static bundle importing](https://github.com/intlify/vite-plugin-vue-i18n#static-bundle-importing) with `import messages from '@intlify/vite-plugin-vue-i18n/messages'`

**Comment by kazupon** [comment]
Thank you for your feedback!

Currently, `import messages from '@intlify/vite-plugin-vue-i18n/messages'` is not supported HMR.
we'll support it.

**Comment by bokuns** [comment]
> Thank you for your feedback!
> 
> Currently, `import messages from '@intlify/vite-plugin-vue-i18n/messages'` is not supported HMR.
> we'll support it.

So what are the advantages of using ```import messages from '@intlify/vite-plugin-vue-i18n/messages'``` over manual import (despite not being supported HMR)?
